import type { Point } from '../geometry/point';
import type { Polygon } from '../geometry/polygon';
import * as point from '../geometry/point';
import * as polygonModule from '../geometry/polygon';

export interface BezierSegment {
  readonly from: Point;
  readonly cp1: Point;
  readonly cp2: Point;
  readonly to: Point;
}

export interface CurvyShape {
  readonly segments: readonly BezierSegment[];
  readonly originalPolygon: Polygon;
  straighten(): Polygon;
  toCanvasPath(ctx: CanvasRenderingContext2D): void;
}

const CURVE_OFFSET = 0.6;

export function createCurvyShape(poly: Polygon): CurvyShape {
  const verts = poly.vertices;
  const n = verts.length;
  const segments: BezierSegment[] = [];

  for (let i = 0; i < n; i++) {
    const vi = verts[i];
    const vj = verts[(i + 1) % n];
    const edge = point.subtract(vj, vi);
    const edgeLen = point.magnitude(edge);
    const edgeDir = point.scale(edge, 1 / edgeLen);
    const perp: Point = { x: -edgeDir.y, y: edgeDir.x };

    const sign = i % 2 === 0 ? 1 : -1;
    const offset = point.scale(perp, CURVE_OFFSET * sign);

    const third = point.add(vi, point.scale(edge, 1 / 3));
    const twoThirds = point.add(vi, point.scale(edge, 2 / 3));

    segments.push({
      from: { x: vi.x, y: vi.y },
      cp1: point.add(third, offset),
      cp2: point.add(twoThirds, offset),
      to: { x: vj.x, y: vj.y },
    });
  }

  const originalPolygon = polygonModule.clone(poly);

  return {
    segments,
    originalPolygon,
    straighten() {
      return polygonModule.clone(originalPolygon);
    },
    toCanvasPath(ctx: CanvasRenderingContext2D) {
      ctx.beginPath();
      ctx.moveTo(verts[0].x, verts[0].y);
      for (const seg of segments) {
        ctx.bezierCurveTo(seg.cp1.x, seg.cp1.y, seg.cp2.x, seg.cp2.y, seg.to.x, seg.to.y);
      }
      ctx.closePath();
    },
  };
}

// --- Custom edge curve support ---

export interface BezierOffset {
  /** Position along edge [0,1] */
  t: number;
  /** Perpendicular offset from baseline (in normalized units; scaled by edge length) */
  offset: number;
}

export interface EdgeCurveData {
  offsets: BezierOffset[];
}

/**
 * Compute the actual 2D position for a BezierOffset applied to an edge.
 */
function offsetToPoint(
  vi: Point,
  vj: Point,
  edgeDir: Point,
  perp: Point,
  edgeLen: number,
  bo: BezierOffset,
): Point {
  const along = point.add(vi, point.scale(point.subtract(vj, vi), bo.t));
  const perpOffset = point.scale(perp, bo.offset * edgeLen);
  return point.add(along, perpOffset);
}

/**
 * Create a CurvyShape using user-defined custom edge curve data.
 *
 * Input offsets define only the first half of each edge (t ∈ [0, 0.5]).
 * The second half (t ∈ [0.5, 1]) is generated by mirroring: for each
 * user offset at (t, offset), a mirrored offset at (1-t, offset) is added.
 * This ensures adjacent tiles interlock properly.
 *
 * Offset points are converted to 2D and interpolated with a Catmull-Rom spline,
 * producing smooth C1-continuous cubic bezier segments through all points.
 */
export function createCurvyShapeFromCurve(poly: Polygon, curveData: EdgeCurveData): CurvyShape {
  const verts = poly.vertices;
  const n = verts.length;
  const userOffsets = curveData.offsets;

  if (userOffsets.length < 2) {
    throw new Error('EdgeCurveData must contain at least 2 offsets');
  }

  // Mirror user offsets to build the full edge curve (S-shape for interlocking)
  // Each user offset (t, offset) → mirrored offset (1-t, -offset)
  // This creates an antisymmetric curve so adjacent tiles with flipped
  // perpendicular direction interlock like jigsaw pieces.
  const fullOffsets: BezierOffset[] = [...userOffsets];
  for (let i = userOffsets.length - 1; i >= 0; i--) {
    const bo = userOffsets[i];
    if (bo.t < 0.5) {
      fullOffsets.push({ t: 1 - bo.t, offset: -bo.offset });
    }
  }
  fullOffsets.sort((a, b) => a.t - b.t);

  for (const fo of fullOffsets) {
    fo.offset = Math.max(-0.5, Math.min(0.5, fo.offset));
  }

  // Ensure endpoints
  if (fullOffsets[0].t > 0) fullOffsets.unshift({ t: 0, offset: 0 });
  if (fullOffsets[fullOffsets.length - 1].t < 1) fullOffsets.push({ t: 1, offset: 0 });

  const segments: BezierSegment[] = [];

  for (let i = 0; i < n; i++) {
    const vi = verts[i];
    const vj = verts[(i + 1) % n];
    const edge = point.subtract(vj, vi);
    const edgeLen = point.magnitude(edge);
    const edgeDir = point.scale(edge, 1 / edgeLen);
    const perp: Point = { x: -edgeDir.y, y: edgeDir.x };

    const pts = fullOffsets.map((bo) => offsetToPoint(vi, vj, edgeDir, perp, edgeLen, bo));

    const edgeSegs = catmullRomToBezierSegments(pts);
    // Clamp bezier control points' perpendicular offset to ±0.5·edgeLen
    // to prevent Catmull-Rom spline overshoot
    for (const seg of edgeSegs) {
      segments.push({
        from: seg.from,
        cp1: clampPerp(seg.cp1, vi, edgeDir, perp, edgeLen),
        cp2: clampPerp(seg.cp2, vi, edgeDir, perp, edgeLen),
        to: seg.to,
      });
    }
  }

  const originalPolygon = polygonModule.clone(poly);

  return {
    segments,
    originalPolygon,
    straighten() {
      return polygonModule.clone(originalPolygon);
    },
    toCanvasPath(ctx: CanvasRenderingContext2D) {
      ctx.beginPath();
      ctx.moveTo(verts[0].x, verts[0].y);
      for (const seg of segments) {
        ctx.bezierCurveTo(seg.cp1.x, seg.cp1.y, seg.cp2.x, seg.cp2.y, seg.to.x, seg.to.y);
      }
      ctx.closePath();
    },
  };
}

/**
 * Convert N ordered 2D points into N-1 cubic bezier segments using
 * Catmull-Rom (Cardinal, tension=0) spline interpolation.
 *
 * For each adjacent pair P[i], P[i+1] the Catmull-Rom control quad
 * [P[i-1], P[i], P[i+1], P[i+2]] is converted to a cubic bezier:
 *   cp1 = P[i]   + (P[i+1] - P[i-1]) / 6
 *   cp2 = P[i+1] - (P[i+2] - P[i])   / 6
 *
 * Phantom points are used at the boundaries:
 *   P[-1]  = 2·P[0] - P[1]       (reflection)
 *   P[N]   = 2·P[N-1] - P[N-2]   (reflection)
 */
function clampPerp(
  cp: Point, vi: Point, edgeDir: Point, perp: Point, edgeLen: number,
): Point {
  const delta = point.subtract(cp, vi);
  const along = delta.x * edgeDir.x + delta.y * edgeDir.y;
  const perpVal = delta.x * perp.x + delta.y * perp.y;
  const limit = 0.5 * edgeLen;
  const clamped = Math.max(-limit, Math.min(limit, perpVal));
  return {
    x: vi.x + along * edgeDir.x + clamped * perp.x,
    y: vi.y + along * edgeDir.y + clamped * perp.y,
  };
}

function catmullRomToBezierSegments(pts: Point[]): BezierSegment[] {
  const N = pts.length;

  if (N < 2) {
    throw new Error('Need at least 2 points for Catmull-Rom spline');
  }

  if (N === 2) {
    const from = pts[0];
    const to = pts[1];
    const cp1 = point.lerp(from, to, 1 / 3);
    const cp2 = point.lerp(from, to, 2 / 3);
    return [{
      from: { x: from.x, y: from.y },
      cp1,
      cp2,
      to: { x: to.x, y: to.y },
    }];
  }

  const ext: Point[] = [
    point.subtract(point.scale(pts[0], 2), pts[1]),
    ...pts,
    point.subtract(point.scale(pts[N - 1], 2), pts[N - 2]),
  ];

  const segments: BezierSegment[] = [];

  for (let i = 0; i < N - 1; i++) {
    const p0 = ext[i];
    const p1 = ext[i + 1];
    const p2 = ext[i + 2];
    const p3 = ext[i + 3];

    const cp1 = point.add(p1, point.scale(point.subtract(p2, p0), 1 / 6));
    const cp2 = point.subtract(p2, point.scale(point.subtract(p3, p1), 1 / 6));

    segments.push({
      from: { x: p1.x, y: p1.y },
      cp1: { x: cp1.x, y: cp1.y },
      cp2: { x: cp2.x, y: cp2.y },
      to: { x: p2.x, y: p2.y },
    });
  }

  return segments;
}
